# Generated by Django 6.0.4 on 2026-04-09 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacao', '0001_initial'),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='veiculo.veiculo'),
        ),
    ]
