# Generated by Django 6.0.4 on 2026-04-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id_plano', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao_dias', models.IntegerField()),
            ],
            options={
                'db_table': 'plano',
            },
        ),
    ]
