# Generated by Django 6.0.4 on 2026-04-09 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id_veiculo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Manutenção')], default='disponivel', max_length=20)),
                ('bateria', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('localizacao_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_atuais', to='localizacao.localizacao')),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
    ]
