# Generated by Django 6.0.4 on 2026-04-09 01:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='carteira.carteira')),
            ],
            options={
                'db_table': 'transacao',
            },
        ),
    ]
