# Generated by Django 6.0.4 on 2026-04-09 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corrida', '0001_initial'),
        ('localizacao', '0001_initial'),
        ('usuario', '0001_initial'),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='localizacao_fim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_fim', to='localizacao.localizacao'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='localizacao_inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas_inicio', to='localizacao.localizacao'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to='veiculo.veiculo'),
        ),
    ]
